%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\cmackey\Documents\AttnTuning\Kiki_Abby_expts.xls
%    Worksheet: FitParams
%
% Auto-generated by MATLAB on 06-Feb-2024 14:36:54

%% Setup the Import Options
clear
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = "FitParams";
opts.DataRange = "J2:P40";

% Specify column names and types
opts.VariableNames = ["site1", "ampratio", "meanratio", "widthratio", "asympratio", "bf1", "area1"];
opts.SelectedVariableNames = ["site1", "ampratio", "meanratio", "widthratio", "asympratio", "bf1", "area1"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");

% Import the data
KikiAbbyexptsS1 = readtable("C:\Users\cmackey\Documents\AttnTuning\Kiki_Abby_expts.xls", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%% fit a lmem

plain = fitlme(KikiAbbyexptsS1,'ampratio~bf1+area1+(1|site1)')

interaction = fitlme(KikiAbbyexptsS1,'ampratio~area1+bf1+(1|site1)')
% 
plain_width = fitlme(KikiAbbyexptsS1,'widthratio~bf1+area1+(1|site1)')

% 
% % lin reg to visualize
linreg=fitlm(KikiAbbyexptsS1,'widthratio~bf1+area1')
% linreg=fitlm(KikiAbbyexptsS4,'width~bf+attn*area')