%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\cmackey\Documents\AttnTuning\Kiki_Abby_expts.xls
%    Worksheet: FitParams
%
% Auto-generated by MATLAB on 24-Jan-2024 10:48:54

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = "FitParams";
opts.DataRange = "A2:H79";

% Specify column names and types
opts.VariableNames = ["site", "amp", "mean", "width", "asymp", "attn", "bf", "area"];
opts.SelectedVariableNames = ["site", "amp", "mean", "width", "asymp", "attn", "bf", "area"];
opts.VariableTypes = ["categorical", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");

% Import the data
KikiAbbyexptsS4 = readtable("C:\Users\cmackey\Documents\AttnTuning\Kiki_Abby_expts.xls", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%% fit a lmem

plain = fitlme(KikiAbbyexptsS4,'amp~attn+bf+area+(1|site)')

interaction = fitlme(KikiAbbyexptsS4,'amp~attn*area+bf+(1|site)')

width_plain = fitlme(KikiAbbyexptsS4,'width~attn+bf+area+(1|site)')

width_interacation = fitlme(KikiAbbyexptsS4,'width~attn*area+bf+(1|site)')

% lin reg to visualize
linreg=fitlm(KikiAbbyexptsS4,'width~attn+bf+area')
linreg=fitlm(KikiAbbyexptsS4,'width~bf+attn*area')